#!/usr/bin/env node
// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 Zixiao Wang

/**
 * Build the Cloudflare Pages deploy root for the geo-sonification frontend.
 *
 * Output:  dist/
 *   - frontend/* copied verbatim (HTML, JS, CSS, audio/cities/*.m4a, ...)
 *   - data/cities.json copied in so the announcer's fetch(`${BASE_PATH}/data/cities.json`)
 *     resolves to a same-origin asset on Pages
 *   - config.runtime.js regenerated with production URLs + Mapbox token
 *
 * Configuration source (precedence: process.env > .env.deploy):
 *   MAPBOX_TOKEN, BASE_PATH, API_BASE, WS_URL, ASSET_BASE
 *
 * Usage:  node scripts/build-pages.js
 */

'use strict';

const { execSync } = require('node:child_process');
const fs = require('node:fs');
const path = require('node:path');

const projectRoot = path.resolve(__dirname, '..');
const distDir = path.join(projectRoot, 'dist');
const frontendDir = path.join(projectRoot, 'frontend');
const citiesSrc = path.join(projectRoot, 'data', 'cities.json');

// ---- Load .env.deploy (optional; process.env wins) ---------------------

const envDeployPath = path.join(projectRoot, '.env.deploy');
const fileEnv = Object.create(null);
if (fs.existsSync(envDeployPath)) {
    for (const line of fs.readFileSync(envDeployPath, 'utf8').split(/\r?\n/)) {
        const trimmed = line.trim();
        if (!trimmed || trimmed.startsWith('#')) continue;
        const eq = trimmed.indexOf('=');
        if (eq < 0) continue;
        const key = trimmed.slice(0, eq).trim();
        const value = trimmed
            .slice(eq + 1)
            .trim()
            .replace(/^["']|["']$/g, '');
        fileEnv[key] = value;
    }
}
const get = (k) => process.env[k] ?? fileEnv[k] ?? '';

const REQUIRED = ['MAPBOX_TOKEN', 'BASE_PATH', 'API_BASE', 'WS_URL', 'ASSET_BASE'];
const missing = REQUIRED.filter((k) => !get(k));
if (missing.length > 0) {
    console.error(`ERROR: missing deploy env vars: ${missing.join(', ')}`);
    console.error('Set them in process.env or in .env.deploy at the project root.');
    console.error('See .env.deploy.example for the template.');
    process.exit(1);
}

// ---- Fresh dist/ -------------------------------------------------------

console.log(`[build-pages] Cleaning ${path.relative(projectRoot, distDir)}/`);
fs.rmSync(distDir, { recursive: true, force: true });
fs.mkdirSync(distDir, { recursive: true });

// ---- Copy frontend/ → dist/ -------------------------------------------

// Exclude directories that live on R2 rather than Pages. The ambience
// WAVs are ~46 MB each — far over Pages' 25 MB per-file ceiling — and
// audio-engine.js fetches them from ASSET_BASE (R2) in production
// anyway. Cities M4A clips (~8 KB each, 555 files) stay in dist/.
console.log('[build-pages] Copying frontend/ → dist/ (skipping audio/ambience/)');
const excludedRelative = new Set([path.join('audio', 'ambience')]);
fs.cpSync(frontendDir, distDir, {
    recursive: true,
    filter: (src) => {
        const rel = path.relative(frontendDir, src);
        return !excludedRelative.has(rel);
    },
});

// ---- Copy data/cities.json → dist/data/cities.json --------------------

console.log('[build-pages] Copying data/cities.json → dist/data/');
fs.mkdirSync(path.join(distDir, 'data'), { recursive: true });
fs.copyFileSync(citiesSrc, path.join(distDir, 'data', 'cities.json'));

// ---- Capture build identity (rule 2.F: frontend bundle build tag) ------

let buildHash = '';
try {
    buildHash = execSync('git rev-parse --short HEAD', {
        cwd: projectRoot,
        encoding: 'utf8',
    }).trim();
} catch (err) {
    console.warn(`[build-pages] git rev-parse failed (${err.message}); leaving buildHash blank`);
}
const buildTime = new Date().toISOString();

// ---- Render dist/config.runtime.js ------------------------------------

const runtimeConfig = {
    basePath: get('BASE_PATH'),
    apiBase: get('API_BASE'),
    wsUrl: get('WS_URL'),
    assetBase: get('ASSET_BASE'),
    mapboxToken: get('MAPBOX_TOKEN'),
    buildHash,
    buildTime,
};
const runtimeContent = `// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 Zixiao Wang
//
// AUTO-GENERATED by scripts/build-pages.js at ${buildTime}.
// Do not commit the generated form — it embeds a production token.

window.GEO_SONIFICATION_CONFIG = ${JSON.stringify(runtimeConfig, null, 4)};
`;
fs.writeFileSync(path.join(distDir, 'config.runtime.js'), runtimeContent);
console.log('[build-pages] Wrote dist/config.runtime.js');

// ---- Also drop a placeholder config.local.js so the <script src> tag
//      in index.html never 404s in production. Production tokens come
//      via GEO_SONIFICATION_CONFIG.mapboxToken already.

fs.writeFileSync(
    path.join(distDir, 'config.local.js'),
    '// Production build: Mapbox token lives in config.runtime.js.\n'
);

// ---- Summary ----------------------------------------------------------

const count = countFiles(distDir);
console.log(`[build-pages] Done. ${count} files in ${path.relative(projectRoot, distDir)}/`);
console.log('[build-pages] Deploy with:  wrangler pages deploy dist/ --project-name=<name>');

function countFiles(dir) {
    let total = 0;
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
        if (entry.isDirectory()) total += countFiles(path.join(dir, entry.name));
        else total += 1;
    }
    return total;
}
